// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMD6-xLWHrwHqVAaZzkHJ2xDbmTUgDSF4',
    appId: '1:172461862295:web:24e9aa193d62514166a8d2',
    messagingSenderId: '172461862295',
    projectId: 'bom-gosto-3588e',
    authDomain: 'bom-gosto-3588e.firebaseapp.com',
    storageBucket: 'bom-gosto-3588e.firebasestorage.app',
    measurementId: 'G-QQM7J5PCQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdWYn4ytKNCZLYBoEdlYSFUNXKbrii5V0',
    appId: '1:172461862295:android:fd2a98147840ac1e66a8d2',
    messagingSenderId: '172461862295',
    projectId: 'bom-gosto-3588e',
    storageBucket: 'bom-gosto-3588e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq1QCXKjkB0Lpf_NbZqUlHKqhnmGJdjsg',
    appId: '1:172461862295:ios:169df8360b13fd9366a8d2',
    messagingSenderId: '172461862295',
    projectId: 'bom-gosto-3588e',
    storageBucket: 'bom-gosto-3588e.firebasestorage.app',
    iosBundleId: 'com.example.bomGosto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq1QCXKjkB0Lpf_NbZqUlHKqhnmGJdjsg',
    appId: '1:172461862295:ios:169df8360b13fd9366a8d2',
    messagingSenderId: '172461862295',
    projectId: 'bom-gosto-3588e',
    storageBucket: 'bom-gosto-3588e.firebasestorage.app',
    iosBundleId: 'com.example.bomGosto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMD6-xLWHrwHqVAaZzkHJ2xDbmTUgDSF4',
    appId: '1:172461862295:web:ee88c0f1d5771d8566a8d2',
    messagingSenderId: '172461862295',
    projectId: 'bom-gosto-3588e',
    authDomain: 'bom-gosto-3588e.firebaseapp.com',
    storageBucket: 'bom-gosto-3588e.firebasestorage.app',
    measurementId: 'G-TELCFMQ00X',
  );
}
